<a href="https://colab.research.google.com/github/SaklenManjire/Ml_Lab/blob/main/Data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split

pd.set_option("display.max_columns",None)
pd.set_option("display.width",100)

# Download latest version
path = kagglehub.dataset_download("brendan45774/test-file")
print("Path to dataset files:", path)
filepath=f"{path}/tested.csv"
df=pd.read_csv(filepath)
print("Intial Dataframe (first 5 rows):")
print(df.head())


# y_target=df['Species']

print("\nExploring data")
df.info()

print("\ndescribe method")
print(df.describe())

print("\nmissing values")
print(df.isnull().sum())

print("\nDrop method")
df_processed=df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'],axis=1)
print(df_processed.head())

print("\nHandling missing values")
print(df_processed.isnull().sum())


age_median=df_processed['Age'].median()
df_processed['Age']=df_processed['Age'].fillna(age_median)
print(f"\nimputing age with median value:{age_median:.2f}")

fare_median=df_processed['Fare'].median()
df_processed['Fare']=df_processed['Fare'].fillna(fare_median)
print(f"imputing fare with median value:{fare_median:.2f}")


print("After handling missing values")
print(df_processed.isnull().sum())


print("\nHandling categorical data")
le=LabelEncoder()
print("\nBefore label encoding (for sex column)")
print(df_processed['Sex'].head)
print("\nfirst the encoder fit and tranform the data")
df_processed['Sex'] = le.fit_transform(df_processed['Sex'])
print(df_processed['Sex'].head)
print(f"classes found for 'sex':{le.classes_} ")

print("\nOne hot encoding('embark column)")
one=OneHotEncoder(sparse_output=False,handle_unknown='ignore')
embark_column=df_processed[['Embarked']]
print("\nBefore")
print(df_processed[['Embarked']].head)


one_hot_column=one.fit_transform(embark_column)
onehot_df=pd.DataFrame(one_hot_column,columns=one.get_feature_names_out(['Embarked']))
onehot_encoded_column=one.fit_transform(df_processed[['Embarked']])
print(onehot_df.head())

df_processed=df_processed.drop('Embarked',axis=1)
df_processed=pd.concat([df_processed,onehot_df],axis=1)


print("\nAfter")
print(df_processed.head())

print("\nAppliying Standardization")
numerical_column=['Age','Fare','SibSp','Parch','Pclass']
scaler=StandardScaler()

print("Before scaling")
print(df_processed[numerical_column].head())
df_processed[numerical_column]=scaler.fit_transform(df_processed[numerical_column])
print("After scaling")
print(df_processed[numerical_column].head())

print("\nSplitting data")
x=df_processed.drop('Survived',axis=1)
y=df_processed['Survived']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)
print("\nDataset has been split into training and testing sets.")
print(f"Shape of X_train: {x_train.shape}")
print(f"Shape of X_test: {x_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

print("\nFirst 5 rows of the final training features (X_train):")
print(x_train.head())

Path to dataset files: /kaggle/input/test-file
Intial Dataframe (first 5 rows):
   PassengerId  Survived  Pclass                                          Name     Sex   Age  \
0          892         0       3                              Kelly, Mr. James    male  34.5
1          893         1       3              Wilkes, Mrs. James (Ellen Needs)  female  47.0
2          894         0       2                     Myles, Mr. Thomas Francis    male  62.0
3          895         0       3                              Wirz, Mr. Albert    male  27.0
4          896         1       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0

   SibSp  Parch   Ticket     Fare Cabin Embarked
0      0      0   330911   7.8292   NaN        Q
1      1      0   363272   7.0000   NaN        S
2      0      0   240276   9.6875   NaN        Q
3      0      0   315154   8.6625   NaN        S
4      1      1  3101298  12.2875   NaN        S

Exploring data
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

describe method
       PassengerId    Survived      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    0.363636    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.481622    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    0.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    0.000000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    0.000000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    1.000000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    1.000000    3.000000   76.000000    8.000000    9.000000  512.329200

missing values
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

Drop method
   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  34.5      0      0   7.8292        Q
1         1       3  female  47.0      1      0   7.0000        S
2         0       2    male  62.0      0      0   9.6875        Q
3         0       3    male  27.0      0      0   8.6625        S
4         1       3  female  22.0      1      1  12.2875        S

Handling missing values
Survived     0
Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

imputing age with median value:27.00
imputing fare with median value:14.45
After handling missing values
Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

Handling categorical data

Before label encoding (for sex column)
<bound method NDFrame.head of 0        male
1      female
2        male
3        male
4      female
        ...
413      male
414    female
415      male
416      male
417      male
Name: Sex, Length: 418, dtype: object>

first the encoder fit and tranform the data
<bound method NDFrame.head of 0      1
1      0
2      1
3      1
4      0
      ..
413    1
414    0
415    1
416    1
417    1
Name: Sex, Length: 418, dtype: int64>
classes found for 'sex':['female' 'male']

One hot encoding('embark column)

Before
<bound method NDFrame.head of     Embarked
0          Q
1          S
2          Q
3          S
4          S
..       ...
413        S
414        C
415        S
416        S
417        C

[418 rows x 1 columns]>
   Embarked_C  Embarked_Q  Embarked_S
0         0.0         1.0         0.0
1         0.0         0.0         1.0
2         0.0         1.0         0.0
3         0.0         0.0         1.0
4         0.0         0.0         1.0

After
   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_C  Embarked_Q  Embarked_S
0         0       3    1  34.5      0      0   7.8292         0.0         1.0         0.0
1         1       3    0  47.0      1      0   7.0000         0.0         0.0         1.0
2         0       2    1  62.0      0      0   9.6875         0.0         1.0         0.0
3         0       3    1  27.0      0      0   8.6625         0.0         0.0         1.0
4         1       3    0  22.0      1      1  12.2875         0.0         0.0         1.0

Appliying Standardization
Before scaling
    Age     Fare  SibSp  Parch  Pclass
0  34.5   7.8292      0      0       3
1  47.0   7.0000      1      0       3
2  62.0   9.6875      0      0       2
3  27.0   8.6625      0      0       3
4  22.0  12.2875      1      1       3
After scaling
        Age      Fare     SibSp     Parch    Pclass
0  0.386231 -0.497413 -0.499470 -0.400248  0.873482
1  1.371370 -0.512278  0.616992 -0.400248  0.873482
2  2.553537 -0.464100 -0.499470 -0.400248 -0.315819
3 -0.204852 -0.482475 -0.499470 -0.400248  0.873482
4 -0.598908 -0.417492  0.616992  0.619896  0.873482

Splitting data

Dataset has been split into training and testing sets.
Shape of X_train: (334, 9)
Shape of X_test: (84, 9)
Shape of y_train: (334,)
Shape of y_test: (84,)

First 5 rows of the final training features (X_train):
       Pclass  Sex       Age    SibSp     Parch      Fare  Embarked_C  Embarked_Q  Embarked_S
163  0.873482    1 -0.204852 -0.49947 -0.400248 -0.512278         0.0         0.0         1.0
223  0.873482    1 -0.677719 -0.49947 -0.400248 -0.498012         0.0         0.0         1.0
183  0.873482    1 -0.204852 -0.49947 -0.400248 -0.498833         0.0         1.0         0.0
21   0.873482    1 -1.623452 -0.49947  0.619896 -0.580922         0.0         0.0         1.0
111  0.873482    0 -0.204852 -0.49947 -0.400248 -0.498310         0.0         1.0         0.0